
--# oracle SQL Aggregation Questions for sales history table.


--1.count the number of sales transactions for each product.
--2.find the average sale amount for each product.
--3.find the maximum and minimum sale amount for each product.
--4.find the total revenue generated by each product.
---5.count the number of sales transactions for each customer.
--6.find the average sale amount per customer.
--7.find the highest purchase amount for each customer.
--8.find the lowest purchase amount for each customer.
--9.find the total revenue generated by each store location.
--10.count the number of sales transactions for each region.
--11.find the total revenue per region.
--12.find the average sale amount per region.
--13.count the number of sales per month
--14.find the total revenue per month.
--15.find the product that generated the highest revenue.
--16.find the most frequently purchased product.
--17.find the most valuable customer based on total spending.
--18.find the total revenue per sales channel(e.g online vs offline).
--19.count the number of sales for each payment method  .
--20.find the total revenue generated per payment method.
